# Generated by Django 3.2.4 on 2021-07-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='is_villa',
            field=models.BooleanField(default=False),
        ),
    ]
