# Generated by Django 3.2.4 on 2021-07-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roomtype_is_villa'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_waiting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
