# Generated by Django 3.1.7 on 2021-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210810_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_waiting',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
