# Generated by Django 3.1.7 on 2021-06-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id_telegram', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lan', models.CharField(max_length=2, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('bed', models.CharField(max_length=5, null=True)),
                ('baby', models.CharField(max_length=5, null=True)),
                ('pet', models.CharField(max_length=5, null=True)),
                ('breakfast', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('telegram_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_class', models.CharField(default='not important', max_length=15)),
                ('fullName', models.CharField(default=None, max_length=50, null=True)),
                ('phone', models.CharField(default=None, max_length=15, null=True)),
                ('email', models.CharField(default=None, max_length=50, null=True)),
                ('is_firm', models.SmallIntegerField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=20, null=True)),
                ('state', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=None, null=True)),
                ('finish_date', models.DateTimeField(default=None, null=True)),
                ('user_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usertelegram')),
            ],
        ),
    ]
