# Generated by Django 3.1.7 on 2021-06-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_firm',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='is_firm',
        ),
    ]
